[project]
name = "photo-rename"
version = "0.1.0"
description = "Tool to rename photos based on EXIF dates"
authors = ["Krzysztof Lewandowski <krzlew1@gmail.com>"]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pillow>=12.0.0",
    "rich>=14.2.0",
    "typer>=0.20.0",
]
